### ISSUE TITLE
 Invalid data, chunk must be a string or buffer, not object

### ISSUE THREAD

**Issue by willin** [virtoolswebplayer/eslint-vue-js-fixer#3]
```
$ vuefix -d src
net.js:692
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:692:11)
    at eslintfixer (/Users/willin/Desktop/vue-vuex-router-element-webpack-master/node_modules/eslint-vue-js-fixer/lib/eslint-vue-js-fixer.js:27:20)
    at vuefiles.forEach (/Users/willin/Desktop/vue-vuex-router-element-webpack-master/node_modules/eslint-vue-js-fixer/lib/eslint-vue-js-fixer.js:51:40)
    at Array.forEach (<anonymous>)
    at recursive (/Users/willin/Desktop/vue-vuex-router-element-webpack-master/node_modules/eslint-vue-js-fixer/lib/eslint-vue-js-fixer.js:37:14)
    at /Users/willin/Desktop/vue-vuex-router-element-webpack-master/node_modules/recursive-readdir/index.js:64:22
    at /Users/willin/Desktop/vue-vuex-router-element-webpack-master/node_modules/recursive-readdir/index.js:71:20
    at FSReqWrap.oncomplete (fs.js:153:5)
error Command failed with exit code 1.
```

.eslintrc:

```js
module.exports = {
  parser: 'babel-eslint',
  env: {
    browser: true,
    commonjs: true,
    es6: true
  },
  extends: 'airbnb-base',
  plugins: [
    'vue',
    // 'vuefix',

    // 'html'
  ],
  // settings: {
  //   "html/html-extensions": [".html", ".vue"],  // consider .html and .we files as HTML
  // },
  rules: {
    // "vuefix/vuefix": [2, {"auto": true}],
    quotes: [2, 'single'],
    semi: 2,
    'max-len': [1, 120, 2],
    'arrow-body-style': [1, 'as-needed'],
    'comma-dangle': [2, 'never'],
    'no-debugger': 2,
    'no-console': 2,
    'object-curly-spacing': [2, 'always'],
    'no-undef': [1],
    'new-cap': 1,
    'no-param-reassign': 2,
    'global-require': 0,
    'no-mixed-operators': 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-unresolved": 0,
    "import/extensions": 0
  }
};
```

```js
extends: 'airbnb-base',
```

when `standard` no error.

@labnize

**Comment by GaoLoo** [comment]
我也遇到了相同的问题
